### ISSUE TITLE
Duplicate name problem with Lao / lao

### ISSUE THREAD

**Issue by stweil** [tesseract-ocr/tessdata_fast#11] opened 2018-03-09 19:22 UTC
Installations on case insensitive filesystems (macOS, Windows, ...) cannot install both `Lao.traineddata` and `lao.traineddata`. It might also be confusing for users to know the difference between `-l Lao` and `-l lao`.

I suggest to rename the first one. Which name would be fine?

**Comment by Shreeshrii** [comment] 2018-03-10 01:55
I would suggest LaoScript or Lao_Script.

Alternative, Lao_Eng to indicate that it can OCR both lao and eng languages.

**Comment by stweil** [comment] 2018-03-10 07:55
If we choose a new name with "Script": should that suffix be added to all other script data filenames, too? So we would have `LatinScript.traineddata`, for example? Another possible solution would be moving all script data to a subdirectory, so we get `-l script/Lao` or `-l script/Latin`.

**Comment by amitdo** [comment] 2018-03-10 08:49
Duplicate of https://github.com/tesseract-ocr/tessdata_best/issues/10

**Comment by Shreeshrii** [comment] 2018-03-10 08:55
@stweil your suggestion is better.

-l script/Lao or -l script/Latin

**Comment by stweil** [comment] 2018-03-10 08:56
@amitdo, thank you for your hint. I‌ had missed that issue and added macOS to the description above now.

**Comment by stweil** [comment] 2018-03-10 20:15
PR #12 was merged, so this issue is fixed now.

**Closed as completed** 2018-03-10 20:14 UTC
